// src/lib/supplyhouse-email-pdf.ts
import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";

function clean(value: unknown) {
  return String(value || "").replace(/\s+/g, " ").trim();
}

export function decodeBasicHtmlEntities(value: string) {
  return String(value || "")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#34;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/gi, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#(\d+);/g, (_match, code) => {
      const n = Number(code);
      return Number.isFinite(n) ? String.fromCharCode(n) : "";
    });
}

export function htmlToPlainText(htmlOrText: unknown) {
  const raw = String(htmlOrText || "");
  if (!raw) return "";

  const withBreaks = raw
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|div|tr|table|tbody|thead|h1|h2|h3|h4|h5|li)>/gi, "\n")
    .replace(/<\/td>/gi, "  ")
    .replace(/<\/th>/gi, "  ")
    .replace(/<[^>]+>/g, " ");

  return decodeBasicHtmlEntities(withBreaks)
    .split(/\r?\n/g)
    .map((line) => clean(line))
    .filter(Boolean)
    .join("\n");
}

function wrapText(args: {
  text: string;
  font: PDFFont;
  fontSize: number;
  maxWidth: number;
}) {
  const words = String(args.text || "").split(/\s+/g).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    const width = args.font.widthOfTextAtSize(next, args.fontSize);

    if (width <= args.maxWidth || !current) {
      current = next;
      continue;
    }

    lines.push(current);
    current = word;
  }

  if (current) lines.push(current);

  return lines.length ? lines : [""];
}

export async function generateSupplyHouseEmailPdfBuffer(args: {
  subject: string;
  from: string;
  to?: string | null;
  messageId?: string | null;
  receivedAt?: string | null;
  bodyText: string;
}) {
  const pdfDoc = await PDFDocument.create();
  const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const marginX = 48;
  const marginTop = 48;
  const marginBottom = 48;
  const pageWidth = 612;
  const pageHeight = 792;
  const usableWidth = pageWidth - marginX * 2;

  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - marginTop;

  function addPageIfNeeded(heightNeeded: number) {
    if (y - heightNeeded >= marginBottom) return;
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    y = pageHeight - marginTop;
  }

  function drawLine(
    text: string,
    options?: {
      font?: PDFFont;
      size?: number;
      color?: ReturnType<typeof rgb>;
      lineGap?: number;
    },
  ) {
    const size = options?.size || 10;
    const font = options?.font || regular;
    const color = options?.color || rgb(0.13, 0.13, 0.13);
    const lineGap = options?.lineGap ?? 4;

    const wrapped = wrapText({
      text,
      font,
      fontSize: size,
      maxWidth: usableWidth,
    });

    for (const wrappedLine of wrapped) {
      addPageIfNeeded(size + lineGap);
      page.drawText(wrappedLine, {
        x: marginX,
        y,
        size,
        font,
        color,
      });
      y -= size + lineGap;
    }
  }

  function drawSpacer(points = 8) {
    addPageIfNeeded(points);
    y -= points;
  }

  function drawRule() {
    addPageIfNeeded(10);
    page.drawLine({
      start: { x: marginX, y },
      end: { x: pageWidth - marginX, y },
      thickness: 1,
      color: rgb(0.82, 0.82, 0.82),
    });
    y -= 12;
  }

  drawLine("SUPPLYHOUSE EMAIL INVOICE SNAPSHOT", {
    font: bold,
    size: 15,
    color: rgb(0.10, 0.24, 0.42),
    lineGap: 5,
  });
  drawLine("Generated by DCFlow from the supplier email body.", {
    size: 9,
    color: rgb(0.40, 0.40, 0.40),
  });
  drawSpacer(4);
  drawRule();

  drawLine(`Subject: ${clean(args.subject) || "—"}`, { font: bold, size: 10 });
  drawLine(`From: ${clean(args.from) || "—"}`, { size: 9 });
  if (clean(args.to)) drawLine(`To: ${clean(args.to)}`, { size: 9 });
  if (clean(args.receivedAt)) drawLine(`Received: ${clean(args.receivedAt)}`, { size: 9 });
  if (clean(args.messageId)) drawLine(`Message ID: ${clean(args.messageId)}`, { size: 8, color: rgb(0.45, 0.45, 0.45) });

  drawSpacer(8);
  drawRule();
  drawLine("EMAIL BODY", { font: bold, size: 11, color: rgb(0.10, 0.24, 0.42) });
  drawSpacer(4);

  const bodyLines = String(args.bodyText || "")
    .split(/\r?\n/g)
    .map((line) => clean(line))
    .filter(Boolean);

  for (const line of bodyLines) {
    drawLine(line, { size: 9, lineGap: 3 });
  }

  return Buffer.from(await pdfDoc.save());
}
